const state={lang:new URLSearchParams(location.search).get('lang')||localStorage.getItem('yuji-language')||'zh'};
const source={malingue:'https://kiangmalingue.com/zh/artists/%E4%BA%8E%E5%90%89/',sadie:'https://www.sadiecoles.com/artists/yu-ji',palais:'https://palaisdetokyo.com/en/personne/yu-ji/',westbund:'https://www.westbund.com/en/index/EVENTS/detail_453B4N.html',newmuseum:'https://www.newmuseum.org/exhibitions/3267-soft-water-hard-stone',ocma:'https://ocma.art/exhibitions/yu-ji-a-guest-a-host-a-ghost/',cca:'https://cca.berlin/de/program/785/yu-ji-miss-shell-delta-and-two-noughts',pecci:'https://centropecci.it/site/assets/files/1900/relazione_2024.pdf',evaporation:'https://kiangmalingue.com/zh/exhibitions/yu-ji-casey-robbins-ho-king-man-boat-zhang-kojiro-kobayashi-evaporates-2/',artbasel:'https://kiangmalingue.com/zh/exhibitions/2025%E5%B7%B4%E5%A1%9E%E7%88%BE%E8%97%9D%E8%A1%93%E5%B1%95%E5%B7%B4%E5%A1%9E%E7%88%BE%E5%B1%95%E6%9C%83-parcours/',ppow:'https://www.ppowgallery.com/exhibitions/yu-ji',mplus:'https://www.mplus.org.hk/en/exhibitions/sigg-prize-2023/',mplusInterview:'https://www.mplus.org.hk/en/magazine/yu-ji-artist-interview-sigg-prize-2023/',artforum:'https://www.artforum.com.cn/interviews/9522',curamagazine:'https://curamagazine.com/digital/yu-ji-2/',frieze:'https://www.frieze.com/article/yu-ji-wasted-mud-2021',artillery:'https://artillerymag.com/yu-ji/',vimeo:'https://vimeo.com/567068042',living:'https://www.livingcontent.online/interviews/yu-ji',amspace:'https://www.owenslaura.com/wp-content/uploads/2018/10/2017-LEAP-FW.pdf',venice:'https://www.labiennale.org/en/art/2019/partecipants/yu-ji'};
const copy={
 zh:{heroEyebrow:'研究资料档案 / RESEARCH DOSSIER',heroType:'雕塑、装置、行为与影像',heroMeta:'艺术家档案 · 作品、展览、访谈与评论',coverCaption:'封面作品：《石肉—小人物2401》，2024',profileEyebrow:'01 / 艺术家简介',profileTitle:'把身体变成一种物质状态',profileText:'于吉（1985年生于上海）是一位艺术家。她以混凝土、铁、树脂、石膏、植物性材料、影像和行为构成持续变化的现场。她的作品不把雕塑当作封闭的物件，而是让材料、身体、建筑与观看在展览现场彼此牵动。',profileText2:'从《石肉》系列到大型展览项目，于吉反复处理残片、重量、悬置、迁移与未完成状态。她也与合作者共同运营上午艺术空间，使空间组织、协作与临时性成为实践的一部分。',portraitCaption:'于吉肖像',practiceEyebrow:'02 / 核心实践',practiceKicker:'材料 · 身体 · 场所',practiceTitle:'雕塑不是静止的结果，而是现场中不断发生的关系。',practiceText:'于吉的材料保留劳动、搬运、破碎和重新组合的痕迹。作品由此处在实体与事件之间：它们有重量，却不稳定；像身体，却拒绝被还原成单一身份；占据空间，却始终向场所和观众开放。',timelineEyebrow:'03 / 发展脉络与时间线',timelineKicker:'2026 → 2012',timelineTitle:'从近期展览回到持续的材料研究',timelineText:'关键节点按倒序排列；每一张图都连接到对应的机构、画廊或展览来源。',worksEyebrow:'04 / 重要作品',worksKicker:'KEY WORKS',exhibitionsEyebrow:'05 / 展览路径',exhibitionsKicker:'EXHIBITIONS',sourcesEyebrow:'06 / 视频、评论与来源',sourcesKicker:'SOURCE MAP',sourcesTitle:'从艺术家自述到机构与评论现场',sourcesText:'以下页面来自 PDF 档案中列出的原始网页。每个卡片都标明来源机构、日期和原文链接；图片仅作为研究索引使用。',referencesEyebrow:'07 / 参考资料',referencesKicker:'REFERENCES',footerText:'于吉 / Yu Ji 研究资料档案 · 资料截止 2026 年 10 月',backTop:'返回顶部 ↑',nav:{about:'艺术家',timeline:'时间线',works:'作品',sources:'来源'},open:'打开原文',imageSource:'图片来源'},
 en:{heroEyebrow:'ARTIST RESEARCH DOSSIER',heroType:'SCULPTURE, INSTALLATION, PERFORMANCE & MOVING IMAGE',heroMeta:'Artist archive · works, exhibitions, interviews and criticism',coverCaption:'Cover work: Flesh in Stone—Little Figure 2401, 2024',profileEyebrow:'01 / ARTIST PROFILE',profileTitle:'Turning the body into a material condition',profileText:'Yu Ji (born in Shanghai in 1985) is an artist whose practice builds changing situations from concrete, iron, resin, plaster, plant matter, moving image and performance. Rather than treating sculpture as a closed object, she lets material, body, architecture and spectatorship pull against one another in the exhibition site.',profileText2:'From the ongoing Flesh in Stone series to large-scale exhibition projects, Yu Ji returns to fragments, weight, suspension, migration and unfinished states. Her work with am Art Space also makes spatial organisation, collaboration and temporality part of the practice.',portraitCaption:'Portrait of Yu Ji',practiceEyebrow:'02 / CORE PRACTICE',practiceKicker:'MATERIAL · BODY · SITE',practiceTitle:'Sculpture is not a fixed result, but a relation that keeps happening in the site.',practiceText:'Yu Ji’s materials retain traces of labour, transport, breakage and reassembly. The works sit between object and event: they have weight but remain unstable; they resemble bodies without resolving into one identity; they occupy space while staying open to the site and its visitors.',timelineEyebrow:'03 / DEVELOPMENT & TIMELINE',timelineKicker:'2026 → 2012',timelineTitle:'From recent exhibitions back to an ongoing material study',timelineText:'Key moments are arranged from newest to earliest; each image links to its institutional, gallery or exhibition source.',worksEyebrow:'04 / KEY WORKS',worksKicker:'KEY WORKS',exhibitionsEyebrow:'05 / EXHIBITION PATH',exhibitionsKicker:'EXHIBITIONS',sourcesEyebrow:'06 / VIDEO, CRITICISM & SOURCES',sourcesKicker:'SOURCE MAP',sourcesTitle:'From artist statements to institutional and critical contexts',sourcesText:'These pages are the original web sources listed in the PDF dossier. Each card identifies its institution, date and source link; images are used as research indexes.',referencesEyebrow:'07 / REFERENCES',referencesKicker:'REFERENCES',footerText:'Yu Ji research archive · dossier updated October 2026',backTop:'Back to top ↑',nav:{about:'Artist',timeline:'Timeline',works:'Works',sources:'Sources'},open:'Open source',imageSource:'Image source'},
 fr:{heroEyebrow:'DOSSIER DE RECHERCHE / ARTISTE',heroType:'SCULPTURE, INSTALLATION, PERFORMANCE & IMAGE EN MOUVEMENT',heroMeta:'Archive d’artiste · œuvres, expositions, entretiens et critique',coverCaption:'Œuvre de couverture : Flesh in Stone—Little Figure 2401, 2024',profileEyebrow:'01 / PROFIL DE L’ARTISTE',profileTitle:'Faire du corps une condition matérielle',profileText:'Yu Ji (née à Shanghai en 1985) est une artiste dont la pratique compose des situations changeantes à partir du béton, du fer, de la résine, du plâtre, de matières végétales, de l’image en mouvement et de la performance. La sculpture n’est pas un objet fermé : matière, corps, architecture et regardeur se répondent dans le lieu d’exposition.',profileText2:'De la série continue Flesh in Stone aux grands projets d’exposition, Yu Ji revient aux fragments, au poids, à la suspension, à la migration et à l’inachèvement. Son travail avec am Art Space fait aussi de l’organisation de l’espace, de la collaboration et de la temporalité des éléments de sa pratique.',portraitCaption:'Portrait de Yu Ji',practiceEyebrow:'02 / PRATIQUE CENTRALE',practiceKicker:'MATIÈRE · CORPS · SITE',practiceTitle:'La sculpture n’est pas un résultat fixe, mais une relation qui se poursuit dans le lieu.',practiceText:'Les matériaux de Yu Ji gardent les traces du travail, du transport, de la rupture et du réassemblage. Les œuvres se situent entre objet et événement : elles ont un poids mais restent instables ; elles ressemblent à des corps sans se réduire à une identité ; elles occupent l’espace tout en restant ouvertes au lieu et à ses visiteurs.',timelineEyebrow:'03 / DÉVELOPPEMENT & CHRONOLOGIE',timelineKicker:'2026 → 2012',timelineTitle:'Des expositions récentes vers une recherche matérielle continue',timelineText:'Les moments clés sont classés du plus récent au plus ancien ; chaque image renvoie à sa source institutionnelle, galerie ou exposition.',worksEyebrow:'04 / ŒUVRES MAJEURES',worksKicker:'ŒUVRES',exhibitionsEyebrow:'05 / PARCOURS D’EXPOSITION',exhibitionsKicker:'EXPOSITIONS',sourcesEyebrow:'06 / VIDÉOS, CRITIQUE & SOURCES',sourcesKicker:'CARTE DES SOURCES',sourcesTitle:'De la parole de l’artiste aux contextes institutionnels et critiques',sourcesText:'Ces pages sont les sources web originales indiquées dans le dossier PDF. Chaque carte précise l’institution, la date et le lien source ; les images servent d’index de recherche.',referencesEyebrow:'07 / RÉFÉRENCES',referencesKicker:'RÉFÉRENCES',footerText:'Archive de recherche Yu Ji · dossier mis à jour en octobre 2026',backTop:'Retour en haut ↑',nav:{about:'Artiste',timeline:'Chronologie',works:'Œuvres',sources:'Sources'},open:'Ouvrir la source',imageSource:'Source de l’image'}
};
const data={keywords:[['WEIGHT',{zh:'重量',en:'Weight',fr:'Poids'},{zh:'材料的承重感与身体尺度形成空间张力。',en:'Load, scale and bodily measure create spatial tension.',fr:'La charge, l’échelle et la mesure du corps créent une tension spatiale.'}],['FRAGMENTATION',{zh:'碎片',en:'Fragmentation',fr:'Fragmentation'},{zh:'残缺的身体拒绝被还原为单一身份。',en:'The broken body refuses a single identity.',fr:'Le corps fragmenté refuse une identité unique.'}],['SITE',{zh:'现场',en:'Site',fr:'Site'},{zh:'建筑、地面与摆放方式共同构成作品。',en:'Architecture, ground and placement form the work together.',fr:'Architecture, sol et disposition forment ensemble l’œuvre.'}]],timeline:[
 {year:'2026',title:{zh:'Origin of the Tiger / 老虎的起源',en:'Origin of the Tiger',fr:'Origin of the Tiger'},place:{zh:'P·P·O·W，纽约',en:'P·P·O·W, New York',fr:'P·P·O·W, New York'},img:'ppow_installation.webp',url:source.ppow},
 {year:'2025',title:{zh:'巴塞尔艺术展 Parcours',en:'Art Basel Parcours',fr:'Art Basel Parcours'},place:{zh:'巴塞尔艺术展',en:'Art Basel',fr:'Art Basel'},img:'art_basel.webp',url:source.artbasel},
 {year:'2024',title:{zh:'Hide Me in Your Belly / 藏我于你腹中',en:'Hide Me in Your Belly',fr:'Hide Me in Your Belly'},place:{zh:'Centro Pecci，普拉托',en:'Centro Pecci, Prato',fr:'Centro Pecci, Prato'},img:'pecci.webp',url:source.pecci},
 {year:'2023',title:{zh:'Miss Shell, Delta, and Two Noughts',en:'Miss Shell, Delta, and Two Noughts',fr:'Miss Shell, Delta, and Two Noughts'},place:{zh:'CCA Berlin，柏林',en:'CCA Berlin',fr:'CCA Berlin'},img:'cca_berlin.webp',url:source.cca},
 {year:'2021',title:{zh:'即兴判断 II / Spontaneous Decisions II',en:'Spontaneous Decisions II',fr:'Spontaneous Decisions II'},place:{zh:'西岸美术馆，上海',en:'West Bund Museum, Shanghai',fr:'West Bund Museum, Shanghai'},img:'west_bund.webp',url:source.westbund},
 {year:'2019',title:{zh:'第58届威尼斯双年展',en:'58th Venice Biennale',fr:'58e Biennale de Venise'},place:{zh:'愿你生活在有趣的时代',en:'May You Live in Interesting Times',fr:'May You Live in Interesting Times'},img:'hugo_boss.webp',url:source.venice},
 {year:'2012—',title:{zh:'石肉 / Flesh in Stone',en:'Flesh in Stone',fr:'Flesh in Stone'},place:{zh:'持续进行的材料与身体研究',en:'An ongoing study of material and body',fr:'Recherche continue sur la matière et le corps'},img:'flesh_stone_2020.webp',url:source.malingue}],
 works:[
 {meta:{zh:'2012—持续进行 · 混凝土、石膏、铁、钢筋',en:'2012—ongoing · concrete, plaster, iron, rebar',fr:'2012—en cours · béton, plâtre, fer, armature'},title:{zh:'石肉 / Flesh in Stone',en:'Flesh in Stone',fr:'Flesh in Stone'},desc:{zh:'残片般的身体在混凝土与铁的重量中形成。作品既像建筑构件，也像身体被搬运后留下的遗留物。',en:'Fragment-like bodies take shape through the weight of concrete and iron. They read as architectural parts and as bodily remnants after transport.',fr:'Des corps fragmentaires prennent forme dans le poids du béton et du fer. Ils évoquent à la fois des éléments architecturaux et des restes corporels déplacés.'},img:'flesh_stone_2020.webp',url:source.malingue},
 {meta:{zh:'2020 · 混凝土、钢材与现场结构',en:'2020 · concrete, steel and site structures',fr:'2020 · béton, acier et structures du site'},title:{zh:'石肉—流动的盛宴 No.2',en:'Flesh in Stone — The Moving Feast No.2',fr:'Flesh in Stone — The Moving Feast No.2'},desc:{zh:'体量、悬挂和身体残片共同构成一个依靠重力维持的临界现场。',en:'Mass, suspension and bodily fragments form a threshold situation held together by gravity.',fr:'Masse, suspension et fragments corporels forment une situation limite tenue par la gravité.'},img:'banquet_2020.webp',url:source.malingue},
 {meta:{zh:'约2012年起 · 水泥、苔藓、树脂、头发',en:'c. 2012 onward · concrete, moss, resin and hair',fr:'depuis 2012 · béton, mousse, résine et cheveux'},title:{zh:'Ta Jama 系列',en:'Ta Jama series',fr:'Série Ta Jama'},desc:{zh:'工业材料获得近似自然石头的表面，生长、腐败与触觉的想象在粗糙体量中相互渗透。',en:'Industrial material takes on the surface of natural stone, letting growth, decay and touch meet in a rough mass.',fr:'La matière industrielle prend la surface d’une pierre naturelle ; croissance, décomposition et toucher se mêlent dans une masse rugueuse.'},img:'ta_jama_correct.webp',url:source.malingue},
 {meta:{zh:'2017 · 铁链、树脂、松香、油灰 · 尺寸可变',en:'2017 · chain, resin, rosin and putty · variable dimensions',fr:'2017 · chaîne, résine, colophane et mastic · dimensions variables'},title:{zh:'练习曲—慢板乐章 IV / Lento',en:'Etude — Lento IV',fr:'Étude — Lento IV'},desc:{zh:'链条、树脂与悬挂结构将雕塑从稳定物件转成持续回应空间的姿态。',en:'Chain, resin and suspension shift sculpture from a stable object into a posture that keeps answering the space.',fr:'Chaîne, résine et suspension font passer la sculpture d’un objet stable à une posture qui répond sans cesse à l’espace.'},img:'hugo_boss.webp',url:source.malingue},
 {meta:{zh:'2020年前后 · 不锈钢、丝网印刷、混合材料',en:'c. 2020 · stainless steel, screenprint and mixed materials',fr:'vers 2020 · acier inoxydable, sérigraphie et matériaux mixtes'},title:{zh:'光滑的静物 / Refined Still Life',en:'Refined Still Life',fr:'Refined Still Life'},desc:{zh:'反射表面与被压缩的图像形成不稳定的观看界面，让物件、身体与场所彼此错位。',en:'Reflective surfaces and compressed images create an unstable viewing interface between object, body and site.',fr:'Surfaces réfléchissantes et images aplaties forment une interface instable entre objet, corps et site.'},img:'taipei_biennial.webp',url:source.malingue}],
 exhibitions:[
 {year:'2024',title:{zh:'蒸发',en:'Evaporation',fr:'Evaporation'},place:{zh:'马凌画廊，香港',en:'Kiang Malingue, Hong Kong',fr:'Kiang Malingue, Hong Kong'},img:'evaporation_hk.webp',url:source.evaporation},
 {year:'2023',title:{zh:'一客，一主，一幽灵',en:'A Guest, A Host, A Ghost',fr:'A Guest, A Host, A Ghost'},place:{zh:'橙县美术馆，科斯塔梅萨',en:'Orange County Museum of Art, Costa Mesa',fr:'Orange County Museum of Art, Costa Mesa'},img:'ocma.webp',url:source.ocma},
 {year:'2023',title:{zh:'Miss Shell, Delta, and Two Noughts',en:'Miss Shell, Delta, and Two Noughts',fr:'Miss Shell, Delta, and Two Noughts'},place:{zh:'CCA Berlin，柏林',en:'CCA Berlin',fr:'CCA Berlin'},img:'cca_berlin.webp',url:source.cca},
 {year:'2021',title:{zh:'即兴判断 II',en:'Spontaneous Decisions II',fr:'Spontaneous Decisions II'},place:{zh:'西岸美术馆展厅 0，上海',en:'Gallery 0, West Bund Museum, Shanghai',fr:'Gallery 0, West Bund Museum, Shanghai'},img:'west_bund.webp',url:source.westbund},
 {year:'2021',title:{zh:'软水硬石',en:'Soft Water Hard Stone',fr:'Soft Water Hard Stone'},place:{zh:'第五届新美术馆三年展，纽约',en:'New Museum Triennial, New York',fr:'Triennale du New Museum, New York'},img:'new_museum.webp',url:source.newmuseum},
 {year:'2024',title:{zh:'Hide Me in Your Belly / 藏我于你腹中',en:'Hide Me in Your Belly',fr:'Hide Me in Your Belly'},place:{zh:'Centro Pecci，普拉托',en:'Centro Pecci, Prato',fr:'Centro Pecci, Prato'},img:'pecci.webp',url:source.pecci}],
 sources:[
 {type:{zh:'视频访谈 · M+',en:'VIDEO INTERVIEW · M+',fr:'ENTRETIEN VIDÉO · M+'},title:{zh:'于吉：物料流动',en:'Yu Ji: Materials in Motion',fr:'Yu Ji : Materials in Motion'},date:'2023.09.25',desc:{zh:'以希克奖 2023 展览为背景，讨论雕塑、回收、重量、体积与材料和空间的关系。',en:'Against the Sigg Prize 2023 exhibition, Yu Ji discusses sculpture, recycling, weight, volume and material-space relations.',fr:'Dans le contexte du Sigg Prize 2023, Yu Ji parle de sculpture, recyclage, poids, volume et relations entre matière et espace.'},img:'mplus_hick.webp',url:source.mplusInterview},
 {type:{zh:'视频访谈 · Vimeo',en:'VIDEO INTERVIEW · VIMEO',fr:'ENTRETIEN VIDÉO · VIMEO'},title:{zh:'于吉与 Jo-ey Tang 对谈',en:'Yu Ji in conversation with Jo-ey Tang',fr:'Yu Ji en conversation avec Jo-ey Tang'},date:'2021.06.11',desc:{zh:'围绕 Chisenhale Gallery 委托项目《Wasted Mud》，讨论城市废墟、流动的水、工作室材料与观众身体。',en:'A conversation around Wasted Mud at Chisenhale Gallery, touching on ruins, moving water, studio materials and the visitor’s body.',fr:'Une conversation autour de Wasted Mud à Chisenhale Gallery, entre ruines, eau en mouvement, matériaux d’atelier et corps du visiteur.'},img:'ica_exhibition.webp',url:source.vimeo},
 {type:{zh:'访谈 · 艺术论坛中文网',en:'INTERVIEW · ARTFORUM CHINA',fr:'ENTRETIEN · ARTFORUM CHINA'},title:{zh:'于吉谈“黑山”',en:'Yu Ji on Black Mountain',fr:'Yu Ji à propos de Black Mountain'},date:'2016.05.18',desc:{zh:'以北京公社个展《黑山》为中心，讨论空间、雕塑、材料、身体行动与未完成状态。',en:'An interview around Black Mountain, discussing space, sculpture, material, bodily action and unfinished states.',fr:'Un entretien autour de Black Mountain sur l’espace, la sculpture, la matière, l’action corporelle et l’inachèvement.'},img:'ta_jama.webp',url:source.artforum},
 {type:{zh:'评论 · CURA.',en:'CRITICISM · CURA.',fr:'CRITIQUE · CURA.'},title:{zh:'Yu Ji — Against Shadows',en:'Yu Ji — Against Shadows',fr:'Yu Ji — Against Shadows'},date:'2022',desc:{zh:'将雕塑、装置、影像和行为放在同一条实践线上，强调身体既是对象，也是行动被压缩后的表达。',en:'Places sculpture, installation, moving image and performance on one line, treating the body as both object and compressed action.',fr:'Réunit sculpture, installation, image en mouvement et performance, en pensant le corps comme objet et action comprimée.'},img:'mplus_hick.webp',url:source.curamagazine},
 {type:{zh:'评论 · Frieze',en:'CRITICISM · FRIEZE',fr:'CRITIQUE · FRIEZE'},title:{zh:'Yu Ji’s Poetic Approach to Mapping Cities and Ideas',en:'Yu Ji’s Poetic Approach to Mapping Cities and Ideas',fr:'Yu Ji : cartographier villes et idées'},date:'2021.06.01',desc:{zh:'以《Wasted Mud》为中心，把展览理解为一种关于城市依存关系的诗性制图。',en:'Reads Wasted Mud as a poetic mapping of urban dependencies, connecting sculpture to water, markets, ruins and others.',fr:'Lit Wasted Mud comme une cartographie poétique des dépendances urbaines, entre eau, marchés, ruines et altérité.'},img:'west_bund.webp',url:source.frieze},
 {type:{zh:'评论 · Artillery Magazine',en:'CRITICISM · ARTILLERY MAGAZINE',fr:'CRITIQUE · ARTILLERY MAGAZINE'},title:{zh:'YU JI',en:'YU JI',fr:'YU JI'},date:'2021.07.07',desc:{zh:'评述《Wasted Mud》中的黑色网、建筑碎片、水泵和身体雕塑，把展厅看成彼此牵连的生态系统。',en:'Discusses the black net, architectural fragments, pumps and bodily sculpture in Wasted Mud as an interconnected ecology.',fr:'Analyse filet noir, fragments architecturaux, pompes et sculptures corporelles comme une écologie interdépendante.'},img:'portrait_installation.webp',url:source.artillery}],
 refs:[
 {title:{zh:'艺术家与画廊',en:'Artist & galleries',fr:'Artiste & galeries'},items:[['Kiang Malingue',source.malingue],['Sadie Coles HQ',source.sadie],['P·P·O·W',source.ppow],['Palais de Tokyo',source.palais],['am Art Space / background',source.amspace]]},
 {title:{zh:'机构与展览',en:'Institutions & exhibitions',fr:'Institutions & expositions'},items:[['West Bund Museum',source.westbund],['New Museum',source.newmuseum],['Orange County Museum of Art',source.ocma],['CCA Berlin',source.cca],['Centro Pecci',source.pecci],['Art Basel Parcours',source.artbasel]]},
 {title:{zh:'视频与评论',en:'Video & criticism',fr:'Vidéo & critique'},items:[['M+ artist interview',source.mplusInterview],['Vimeo / Chisenhale Gallery',source.vimeo],['Artforum China',source.artforum],['CURA.',source.curamagazine],['Frieze',source.frieze],['Artillery Magazine',source.artillery]]}]
};
const pick=value=>value?.[state.lang]??value?.zh??value??'';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
copy.zh.artistName='于吉';copy.en.artistName='Yu Ji';copy.fr.artistName='Yu Ji';copy.zh.footerText='于吉研究资料档案 · 资料截止 2026 年 10 月';
data.keywords.push(
 ['MIGRATION',{zh:'迁移',en:'Migration',fr:'Migration'},{zh:'材料、身体和观看经验都处于移动之中。',en:'Material, body and spectatorship remain in motion.',fr:'Matière, corps et regard restent en mouvement.'}],
 ['BODY',{zh:'身体',en:'Body',fr:'Corps'},{zh:'身体既是尺度，也是被材料重新组织的现场。',en:'The body is both a measure and a site reorganised by material.',fr:'Le corps est à la fois mesure et lieu réorganisé par la matière.'}],
 ['MATERIALITY',{zh:'物质性',en:'Materiality',fr:'Matérialité'},{zh:'作品让物质的重量、阻力与表面成为叙事。',en:'Weight, resistance and surface become narrative forces.',fr:'Poids, résistance et surface deviennent des forces narratives.'}],
 ['SUSPENSION',{zh:'悬置',en:'Suspension',fr:'Suspension'},{zh:'悬挂与失衡让作品保持未完成的张力。',en:'Hanging and imbalance keep the work in unfinished tension.',fr:'L’accrochage et le déséquilibre maintiennent une tension inachevée.'}],
 ['TRANSFORMATION',{zh:'转化',en:'Transformation',fr:'Transformation'},{zh:'材料在物件、身体与事件之间不断转化。',en:'Material continually shifts between object, body and event.',fr:'La matière se transforme entre objet, corps et événement.'}],
 ['TEMPORALITY',{zh:'时间性',en:'Temporality',fr:'Temporalité'},{zh:'作品把制作、衰变和观看的时间并置。',en:'Making, decay and looking are held together in time.',fr:'La fabrication, la dégradation et le regard coexistent dans le temps.'}],
 ['SPECTATORSHIP',{zh:'观看',en:'Spectatorship',fr:'Regard'},{zh:'观众的移动改变作品在空间中的关系。',en:'The visitor’s movement changes the work’s spatial relations.',fr:'Le déplacement du visiteur modifie les relations spatiales de l’œuvre.'}],
 ['RELATIONALITY',{zh:'关系性',en:'Relationality',fr:'Relationnalité'},{zh:'作品通过人与物、空间与制度之间的关系生成。',en:'The work emerges through relations between people, things, sites and institutions.',fr:'L’œuvre naît des relations entre personnes, choses, lieux et institutions.'}],
 ['NARRATIVE',{zh:'叙事',en:'Narrative',fr:'Récit'},{zh:'碎片化线索让故事保持开放而非封闭。',en:'Fragmented clues keep the story open rather than closed.',fr:'Des indices fragmentaires gardent le récit ouvert.'}]
);
function renderKeywords(){document.querySelector('#keywordGrid').innerHTML=data.keywords.map(([code,name,desc],i)=>`<article class="keyword"><b>${String(i+1).padStart(2,'0')} / ${esc(code)}</b><strong>${esc(pick(name))}</strong><p>${esc(pick(desc))}</p></article>`).join('')}
function renderTimeline(){document.querySelector('#timelineTrack').innerHTML=data.timeline.map(item=>`<article class="timeline-card"><a href="${item.url}" target="_blank" rel="noreferrer"><figure><img src="${item.img}" alt="${esc(pick(item.title))}" loading="lazy"><figcaption><time>${item.year}</time><strong>${esc(pick(item.title))}</strong><small>${esc(pick(item.place))}</small></figcaption></figure></a><a class="image-source" href="${item.url}" target="_blank" rel="noreferrer">${esc(copy[state.lang].imageSource)} ↗</a></article>`).join('')}
function renderWorks(){document.querySelector('#worksGrid').innerHTML=data.works.map((item,i)=>`<article class="work-card"><a href="${item.url}" target="_blank" rel="noreferrer"><figure><img src="${item.img}" alt="${esc(pick(item.title))}" loading="lazy"><figcaption><span>${esc(copy[state.lang].imageSource)}</span><span>0${i+1} ↗</span></figcaption></figure></a><div class="card-copy"><div class="card-meta"><span>${esc(pick(item.meta))}</span><span>YU JI</span></div><h3>${esc(pick(item.title))}</h3><p>${esc(pick(item.desc))}</p><a class="image-source" href="${item.url}" target="_blank" rel="noreferrer">${esc(copy[state.lang].open)} ↗</a></div></article>`).join('')}
function renderExhibitions(){document.querySelector('#exhibitionList').innerHTML=data.exhibitions.map(item=>`<article class="exhibition"><div class="exhibition-year">${item.year}</div><div><h3>${esc(pick(item.title))}</h3><p>${esc(pick(item.place))}</p><a class="image-source" href="${item.url}" target="_blank" rel="noreferrer">${esc(copy[state.lang].open)} ↗</a></div><a class="exhibition-img" href="${item.url}" target="_blank" rel="noreferrer"><img src="${item.img}" alt="${esc(pick(item.title))}" loading="lazy"></a></article>`).join('')}
function renderSources(){document.querySelector('#sourceGrid').innerHTML=data.sources.map(item=>`<article class="source-card"><a href="${item.url}" target="_blank" rel="noreferrer"><img src="${item.img}" alt="${esc(pick(item.title))}" loading="lazy"></a><div><div class="source-type">${esc(pick(item.type))}</div><h3>${esc(pick(item.title))}</h3><p>${item.date} · ${esc(pick(item.desc))}</p><a href="${item.url}" target="_blank" rel="noreferrer">${esc(copy[state.lang].open)} ↗</a></div></article>`).join('')}
function renderRefs(){document.querySelector('#referenceColumns').innerHTML=data.refs.map(group=>`<section class="reference-column"><h3>${esc(pick(group.title))}</h3><ul>${group.items.map(([label,url])=>`<li><a href="${url}" target="_blank" rel="noreferrer">${esc(label)} ↗</a></li>`).join('')}</ul></section>`).join('')}
function render(){const t=copy[state.lang];document.documentElement.lang=state.lang==='zh'?'zh-CN':state.lang;document.querySelectorAll('[data-copy]').forEach(el=>{const key=el.dataset.copy;if(t[key])el.textContent=t[key]});document.querySelectorAll('[data-nav]').forEach(el=>{el.textContent=t.nav[el.dataset.nav]});document.querySelectorAll('[data-lang]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.lang===state.lang)));renderKeywords();renderTimeline();renderWorks();renderExhibitions();renderSources();renderRefs();document.title=state.lang==='zh'?'于吉 / Yu Ji — 艺术家研究档案':state.lang==='fr'?'Yu Ji — Archive de recherche':'Yu Ji — Artist Research Archive'}
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{state.lang=button.dataset.lang;localStorage.setItem('yuji-language',state.lang);const url=new URL(location.href);url.searchParams.set('lang',state.lang);history.replaceState({},'',url);render()}));
render();
